version: 2

jobs:
  build:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - restore_cache:
          key: terraform-cache-golang
      - run: bash .circleci/dependencies.sh
      - save_cache:
          key: terraform-cache-golang
          paths:
              - ~/terraform
      - run:
          name: Planshots
          command: bash bin/planshots
      - run:
          name: Check fmt
          command: terraform fmt -diff=false -write=false -check=true
